# Generated by Django 5.1.4 on 2025-01-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=50, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[("Men", "Men"), ("Women", "Women")],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("quantity", models.IntegerField(null=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("image", models.ImageField(null=True, upload_to="productImages/")),
            ],
        ),
    ]
