# Generated by Django 5.1.4 on 2025-01-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[("Men", "Men"), ("Women", "Women")], max_length=50, null=True
            ),
        ),
    ]
